vtr_name<-c("a","b","c","d","e","f","9","h","1","j")
vtr_per<-c(87,60,50,98,90,82,78,76,99,92)
x<-c(98,90,99,92)
labels<-c("d","e","i","j")
pie(x,labels,main="student Pie chart",col=rainbow(length(x)))
barplot(vtr_per,names.arg=vtr_name,xlab="students",ylab="Percentage", col="red", main="Student's Bar Chart", border="white")
plot(vtr_per,type = "o",col="green",xlab="students",ylab="Percentage", main="Student's Line Graph")
hist(vtr_per,xlab = "students",ylab="Percentage",col = "darkmagenta",border="white",main="Student's Histogram")
boxplot(vtr_per,data=vtr_per,ylab="Percentage",main="Student Data",notch=FALSE,col="green")